# Generated by Django 3.0.5 on 2020-04-12 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ElementoPatrimonio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(db_index=True, editable=False, max_length=5, null=True)),
                ('numero', models.IntegerField(editable=False, null=True)),
                ('denominacion', models.CharField(max_length=255, null=True)),
                ('denominacion_alt', models.CharField(blank=True, max_length=2000, null=True)),
                ('direccion', models.CharField(max_length=2000, null=True)),
                ('latitud', models.DecimalField(decimal_places=8, max_digits=10, null=True)),
                ('longitud', models.DecimalField(decimal_places=8, max_digits=11, null=True)),
                ('alturas', models.SmallIntegerField(default=0, null=True)),
                ('desaparecido', models.BooleanField(default=False)),
                ('observaciones', models.CharField(blank=True, max_length=2000, null=True)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'CAT_ElementosPatrimonio',
            },
        ),
        migrations.CreateModel(
            name='EstadoConservacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
                ('orden', models.SmallIntegerField(default=0, null=True)),
            ],
            options={
                'db_table': 'CAT_EstadosConservacion',
            },
        ),
        migrations.CreateModel(
            name='Estilo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'CAT_Estilos',
            },
        ),
        migrations.CreateModel(
            name='Riesgo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
                ('orden', models.SmallIntegerField(default=0, null=True)),
            ],
            options={
                'db_table': 'CAT_Riesgos',
            },
        ),
        migrations.CreateModel(
            name='Situacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'CAT_Situaciones',
            },
        ),
        migrations.CreateModel(
            name='Tipologia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'CAT_Tipologias',
            },
        ),
        migrations.CreateModel(
            name='UsoActual',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'CAT_UsosActuales',
            },
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
                ('codigo', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'CAT_Zonas',
            },
        ),
        migrations.CreateModel(
            name='Subzona',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
                ('codigo', models.CharField(max_length=1)),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mto_catalogo.Zona')),
            ],
            options={
                'db_table': 'CAT_Subzonas',
            },
        ),
        migrations.CreateModel(
            name='Subtipologia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
                ('tipologia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mto_catalogo.Tipologia')),
            ],
            options={
                'db_table': 'CAT_Subtipologias',
            },
        ),
        migrations.CreateModel(
            name='Historia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('actuacion', models.CharField(max_length=255, null=True)),
                ('datacion', models.CharField(blank=True, max_length=255, null=True)),
                ('autor', models.CharField(blank=True, max_length=255, null=True)),
                ('elemento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mto_catalogo.ElementoPatrimonio')),
                ('estilo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mto_catalogo.Estilo')),
            ],
            options={
                'db_table': 'CAT_Historia',
            },
        ),
        migrations.AddField(
            model_name='elementopatrimonio',
            name='zona',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='mto_catalogo.Zona'),
        ),
        migrations.AddField(
            model_name='elementopatrimonio',
            name='subzona',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='mto_catalogo.Subzona'),
        ),
        migrations.AddField(
            model_name='elementopatrimonio',
            name='tipologia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mto_catalogo.Tipologia'),
        ),
        migrations.AddField(
            model_name='elementopatrimonio',
            name='subtipologia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mto_catalogo.Subtipologia'),
        ),
        migrations.AddField(
            model_name='elementopatrimonio',
            name='situacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='mto_catalogo.Situacion'),
        ),
        migrations.AddField(
            model_name='elementopatrimonio',
            name='uso_actual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mto_catalogo.UsoActual'),
        ),
        migrations.AddField(
            model_name='elementopatrimonio',
            name='estado_conservacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='mto_catalogo.EstadoConservacion'),
        ),
        migrations.AddField(
            model_name='elementopatrimonio',
            name='riesgo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mto_catalogo.Riesgo'),
        ),
    ]
