# Generated by Django 3.0.5 on 2020-04-26 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mto_catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historia',
            name='ano_desde',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='historia',
            name='ano_hasta',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='historia',
            name='elemento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historia', to='mto_catalogo.ElementoPatrimonio'),
        ),
        migrations.AlterField(
            model_name='subtipologia',
            name='tipologia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtipologias', to='mto_catalogo.Tipologia'),
        ),
        migrations.AlterField(
            model_name='subzona',
            name='zona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subzonas', to='mto_catalogo.Zona'),
        ),
    ]
